<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MahasiswaSeeder extends Seeder
{
    public function run(): void
    {
        // Ambil ID prodi dari DB
        $prodi = DB::table('prodis')->pluck('id', 'kode');

        $mahasiswas = [
            // ── Angkatan 2021 ─────────────────────────
            [
                'prodi_id'     => $prodi['S1-TI']  ?? null,
                'npm'          => '2021001001',
                'nama_lengkap' => 'Ahmad Fauzi Ramadhan',
                'email'        => 'ahmad.fauzi@mahasiswa.ac.id',
                'telepon'      => '081234567001',
                'alamat'       => 'Jl. Gatot Subroto No. 12, Banjarmasin Utara, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2021,
            ],
            [
                'prodi_id'     => $prodi['S1-TI']  ?? null,
                'npm'          => '2021001002',
                'nama_lengkap' => 'Siti Nurhaliza Putri',
                'email'        => 'siti.nurhaliza@mahasiswa.ac.id',
                'telepon'      => '081234567002',
                'alamat'       => 'Jl. A. Yani Km. 5 No. 34, Banjarmasin Selatan, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2021,
            ],
            [
                'prodi_id'     => $prodi['S1-SI']  ?? null,
                'npm'          => '2021002001',
                'nama_lengkap' => 'Muhammad Rizky Pratama',
                'email'        => 'rizky.pratama@mahasiswa.ac.id',
                'telepon'      => '082345678001',
                'alamat'       => 'Jl. Lambung Mangkurat No. 8, Banjarmasin Tengah, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2021,
            ],
            [
                'prodi_id'     => $prodi['S1-SI']  ?? null,
                'npm'          => '2021002002',
                'nama_lengkap' => 'Dewi Rahayu Lestari',
                'email'        => 'dewi.rahayu@mahasiswa.ac.id',
                'telepon'      => '082345678002',
                'alamat'       => 'Jl. Veteran No. 45, Martapura, Banjar, Kalimantan Selatan',
                'status'       => 'cuti',
                'angkatan'     => 2021,
            ],
            [
                'prodi_id'     => $prodi['S1-MN']  ?? null,
                'npm'          => '2021003001',
                'nama_lengkap' => 'Bagas Eko Santoso',
                'email'        => 'bagas.eko@mahasiswa.ac.id',
                'telepon'      => '083456789001',
                'alamat'       => 'Jl. Pangeran Samudera No. 22, Banjarmasin Barat, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2021,
            ],
            [
                'prodi_id'     => $prodi['S1-AK']  ?? null,
                'npm'          => '2021004001',
                'nama_lengkap' => 'Anisa Fitriani Wijaya',
                'email'        => 'anisa.fitriani@mahasiswa.ac.id',
                'telepon'      => '084567890001',
                'alamat'       => 'Jl. S. Parman No. 17, Banjarmasin Timur, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2021,
            ],
            [
                'prodi_id'     => $prodi['S1-TK']  ?? null,
                'npm'          => '2021005001',
                'nama_lengkap' => 'Dimas Arya Nugroho',
                'email'        => 'dimas.arya@mahasiswa.ac.id',
                'telepon'      => '085678901001',
                'alamat'       => 'Jl. Brigjen H. Hasan Basri No. 30, Banjarmasin Utara, Kalimantan Selatan',
                'status'       => 'lulus',
                'angkatan'     => 2021,
            ],
            [
                'prodi_id'     => $prodi['S1-HK']  ?? null,
                'npm'          => '2021006001',
                'nama_lengkap' => 'Rini Safitri Handayani',
                'email'        => 'rini.safitri@mahasiswa.ac.id',
                'telepon'      => '086789012001',
                'alamat'       => 'Jl. Ahmad Yani No. 55, Banjarbaru, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2021,
            ],

            // ── Angkatan 2022 ─────────────────────────
            [
                'prodi_id'     => $prodi['S1-TI']  ?? null,
                'npm'          => '2022001001',
                'nama_lengkap' => 'Kevin Aldi Saputra',
                'email'        => 'kevin.aldi@mahasiswa.ac.id',
                'telepon'      => '087890123001',
                'alamat'       => 'Jl. Jenderal Sudirman No. 10, Banjarmasin, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2022,
            ],
            [
                'prodi_id'     => $prodi['S1-TI']  ?? null,
                'npm'          => '2022001002',
                'nama_lengkap' => 'Nurul Hidayah Azzahra',
                'email'        => 'nurul.hidayah@mahasiswa.ac.id',
                'telepon'      => '087890123002',
                'alamat'       => 'Jl. Antasari No. 66, Banjarmasin Selatan, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2022,
            ],
            [
                'prodi_id'     => $prodi['S1-SI']  ?? null,
                'npm'          => '2022002001',
                'nama_lengkap' => 'Farhan Maulana Ibrahim',
                'email'        => 'farhan.maulana@mahasiswa.ac.id',
                'telepon'      => '088901234001',
                'alamat'       => 'Jl. Soetoyo S. No. 38, Banjarmasin Timur, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2022,
            ],
            [
                'prodi_id'     => $prodi['S1-MN']  ?? null,
                'npm'          => '2022003001',
                'nama_lengkap' => 'Putri Ayu Cahyani',
                'email'        => 'putri.ayu@mahasiswa.ac.id',
                'telepon'      => '089012345001',
                'alamat'       => 'Jl. Pahlawan No. 14, Martapura, Banjar, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2022,
            ],
            [
                'prodi_id'     => $prodi['S1-AK']  ?? null,
                'npm'          => '2022004001',
                'nama_lengkap' => 'Rizal Firmansyah Hakim',
                'email'        => 'rizal.firmansyah@mahasiswa.ac.id',
                'telepon'      => '081123456001',
                'alamat'       => 'Jl. Pemuda No. 9, Banjarbaru Utara, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2022,
            ],
            [
                'prodi_id'     => $prodi['S1-PS']  ?? null,
                'npm'          => '2022007001',
                'nama_lengkap' => 'Aulia Ramadhani Putri',
                'email'        => 'aulia.ramadhani@mahasiswa.ac.id',
                'telepon'      => '082234567001',
                'alamat'       => 'Jl. Kuin Utara No. 25, Banjarmasin Utara, Kalimantan Selatan',
                'status'       => 'cuti',
                'angkatan'     => 2022,
            ],
            [
                'prodi_id'     => $prodi['S1-TE']  ?? null,
                'npm'          => '2022008001',
                'nama_lengkap' => 'Hendro Prabowo Susanto',
                'email'        => 'hendro.prabowo@mahasiswa.ac.id',
                'telepon'      => '083345678001',
                'alamat'       => 'Jl. Sei Besar No. 7, Banjarbaru Selatan, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2022,
            ],
            [
                'prodi_id'     => $prodi['D3-TI']  ?? null,
                'npm'          => '2022009001',
                'nama_lengkap' => 'Melisa Oktavia Sari',
                'email'        => 'melisa.oktavia@mahasiswa.ac.id',
                'telepon'      => '084456789001',
                'alamat'       => 'Jl. Pramuka No. 41, Banjarmasin Selatan, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2022,
            ],

            // ── Angkatan 2023 ─────────────────────────
            [
                'prodi_id'     => $prodi['S1-TI']  ?? null,
                'npm'          => '2023001001',
                'nama_lengkap' => 'Arif Rahman Hakim',
                'email'        => 'arif.rahman@mahasiswa.ac.id',
                'telepon'      => '085567890001',
                'alamat'       => 'Jl. Dharma Praja No. 3, Banjarmasin Barat, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2023,
            ],
            [
                'prodi_id'     => $prodi['S1-TI']  ?? null,
                'npm'          => '2023001002',
                'nama_lengkap' => 'Zahra Nabilah Kusuma',
                'email'        => 'zahra.nabilah@mahasiswa.ac.id',
                'telepon'      => '085567890002',
                'alamat'       => 'Jl. Masjid Jami No. 19, Banjarmasin Tengah, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2023,
            ],
            [
                'prodi_id'     => $prodi['S1-SI']  ?? null,
                'npm'          => '2023002001',
                'nama_lengkap' => 'Galih Setiawan Putra',
                'email'        => 'galih.setiawan@mahasiswa.ac.id',
                'telepon'      => '086678901001',
                'alamat'       => 'Jl. Karang Anyar No. 50, Banjarmasin Tengah, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2023,
            ],
            [
                'prodi_id'     => $prodi['S1-DK']  ?? null,
                'npm'          => '2023003001',
                'nama_lengkap' => 'Indira Permata Sari',
                'email'        => 'indira.permata@mahasiswa.ac.id',
                'telepon'      => '087789012001',
                'alamat'       => 'Jl. Pekapuran Raya No. 28, Banjarmasin Timur, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2023,
            ],
            [
                'prodi_id'     => $prodi['S1-MN']  ?? null,
                'npm'          => '2023004001',
                'nama_lengkap' => 'Yoga Pradana Kusuma',
                'email'        => 'yoga.pradana@mahasiswa.ac.id',
                'telepon'      => '088890123001',
                'alamat'       => 'Jl. Sultan Adam No. 62, Banjarmasin Utara, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2023,
            ],
            [
                'prodi_id'     => $prodi['S1-AK']  ?? null,
                'npm'          => '2023005001',
                'nama_lengkap' => 'Bella Oktaviani Dewi',
                'email'        => 'bella.oktaviani@mahasiswa.ac.id',
                'telepon'      => '089901234001',
                'alamat'       => 'Jl. Simpang Ulin No. 11, Banjarbaru, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2023,
            ],
            [
                'prodi_id'     => $prodi['S1-TS']  ?? null,
                'npm'          => '2023006001',
                'nama_lengkap' => 'Taufik Hidayatullah',
                'email'        => 'taufik.hidayat@mahasiswa.ac.id',
                'telepon'      => '081012345001',
                'alamat'       => 'Jl. Landasan Ulin No. 33, Banjarbaru Utara, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2023,
            ],
            [
                'prodi_id'     => $prodi['D3-AK']  ?? null,
                'npm'          => '2023007001',
                'nama_lengkap' => 'Nadia Fitria Rahmawati',
                'email'        => 'nadia.fitria@mahasiswa.ac.id',
                'telepon'      => '082112345001',
                'alamat'       => 'Jl. Ahmad Yani Km. 33, Banjarbaru Selatan, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2023,
            ],
            [
                'prodi_id'     => $prodi['S1-KM']  ?? null,
                'npm'          => '2023008001',
                'nama_lengkap' => 'Reza Akbar Permana',
                'email'        => 'reza.akbar@mahasiswa.ac.id',
                'telepon'      => '083223456001',
                'alamat'       => 'Jl. Guntung Paikat No. 16, Banjarbaru, Kalimantan Selatan',
                'status'       => 'dropout',
                'angkatan'     => 2023,
            ],

            // ── Angkatan 2024 ─────────────────────────
            [
                'prodi_id'     => $prodi['S1-TI']  ?? null,
                'npm'          => '2024001001',
                'nama_lengkap' => 'Fadhil Akmal Ramadhan',
                'email'        => 'fadhil.akmal@mahasiswa.ac.id',
                'telepon'      => '084334567001',
                'alamat'       => 'Jl. Gubernur Syarkawi No. 5, Banjarmasin, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2024,
            ],
            [
                'prodi_id'     => $prodi['S1-TI']  ?? null,
                'npm'          => '2024001002',
                'nama_lengkap' => 'Salma Aulia Rahma',
                'email'        => 'salma.aulia@mahasiswa.ac.id',
                'telepon'      => '084334567002',
                'alamat'       => 'Jl. Kebun Bunga No. 27, Banjarmasin Timur, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2024,
            ],
            [
                'prodi_id'     => $prodi['S1-SI']  ?? null,
                'npm'          => '2024002001',
                'nama_lengkap' => 'Ilham Maulana Akbar',
                'email'        => 'ilham.maulana@mahasiswa.ac.id',
                'telepon'      => '085445678001',
                'alamat'       => 'Jl. Mantuil Raya No. 44, Banjarmasin Selatan, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2024,
            ],
            [
                'prodi_id'     => $prodi['S1-MN']  ?? null,
                'npm'          => '2024003001',
                'nama_lengkap' => 'Amira Zahwa Fadillah',
                'email'        => 'amira.zahwa@mahasiswa.ac.id',
                'telepon'      => '086556789001',
                'alamat'       => 'Jl. Sei Andai No. 13, Banjarmasin Utara, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2024,
            ],
            [
                'prodi_id'     => $prodi['S1-AK']  ?? null,
                'npm'          => '2024004001',
                'nama_lengkap' => 'Daffa Rizqullah Pratama',
                'email'        => 'daffa.rizqullah@mahasiswa.ac.id',
                'telepon'      => '087667890001',
                'alamat'       => 'Jl. Banua Anyar No. 21, Banjarmasin Timur, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2024,
            ],
            [
                'prodi_id'     => $prodi['S1-PS']  ?? null,
                'npm'          => '2024005001',
                'nama_lengkap' => 'Khairunnisa Putri Andini',
                'email'        => 'khairunnisa.putri@mahasiswa.ac.id',
                'telepon'      => '088778901001',
                'alamat'       => 'Jl. Telawang No. 37, Banjarmasin Barat, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2024,
            ],
            [
                'prodi_id'     => $prodi['D3-MI']  ?? null,
                'npm'          => '2024006001',
                'nama_lengkap' => 'Wahyu Tri Kurniawan',
                'email'        => 'wahyu.tri@mahasiswa.ac.id',
                'telepon'      => '089889012001',
                'alamat'       => 'Jl. Perintis Kemerdekaan No. 8, Banjarmasin Tengah, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2024,
            ],
            [
                'prodi_id'     => $prodi['S1-TE']  ?? null,
                'npm'          => '2024007001',
                'nama_lengkap' => 'Naila Syifa Mardiyah',
                'email'        => 'naila.syifa@mahasiswa.ac.id',
                'telepon'      => '081990123001',
                'alamat'       => 'Jl. Cemara Raya No. 52, Banjarbaru, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2024,
            ],
            [
                'prodi_id'     => $prodi['S1-TK']  ?? null,
                'npm'          => '2024008001',
                'nama_lengkap' => 'Fathan Mubarak Yusuf',
                'email'        => 'fathan.mubarak@mahasiswa.ac.id',
                'telepon'      => '082101234001',
                'alamat'       => 'Jl. Trikora No. 6, Banjarbaru Utara, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2024,
            ],
            [
                'prodi_id'     => $prodi['S1-DK']  ?? null,
                'npm'          => '2024009001',
                'nama_lengkap' => 'Syahrani Meilani Putri',
                'email'        => 'syahrani.meilani@mahasiswa.ac.id',
                'telepon'      => '083212345001',
                'alamat'       => 'Jl. Cempaka No. 29, Martapura, Banjar, Kalimantan Selatan',
                'status'       => 'aktif',
                'angkatan'     => 2024,
            ],
        ];

        foreach ($mahasiswas as $data) {
            DB::table('mahasiswas')->insertOrIgnore(array_merge($data, [
                'created_at' => now()->subDays(rand(1, 400)),
                'updated_at' => now()->subDays(rand(0, 30)),
            ]));
        }

        $this->command->info('✅ ' . count($mahasiswas) . ' data mahasiswa berhasil ditambahkan.');
    }
}
